sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml up --build -d
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml exec web pip freeze

script:
  - docker-compose -f docker-compose.test.yml exec web pytest --cov=src --cov-report term-missing test/

after_success:
  - docker-compose -f docker-compose.test.yml exec web codecov
