version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - FLASK_ENV=testing
      - CODECOV_TOKEN=${CODECOV_TOKEN}
    volumes:
      - .:/usr/src/app
    links:
      - db

  db:
    image: mongo:4.0.3
    ports:
      - "27017:27017"
